apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::942771149643:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::942771149643:role/eksctl-eksctl-demo-nodegroup-ng-6-NodeInstanceRole-1JXI0VCWPURAS
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-02T10:49:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1645"
  uid: db0be72b-78f1-46eb-81f5-8b126e5bd88b
